set(_CATKIN_CURRENT_PACKAGE "um6")
set(um6_VERSION "1.1.2")
set(um6_MAINTAINER "Mike Purvis <mpurvis@clearpathrobotics.com>")
set(um6_PACKAGE_FORMAT "1")
set(um6_BUILD_DEPENDS "serial" "roscpp" "roslint" "sensor_msgs" "message_generation")
set(um6_BUILD_EXPORT_DEPENDS "serial" "roscpp" "sensor_msgs" "message_runtime")
set(um6_BUILDTOOL_DEPENDS "catkin")
set(um6_BUILDTOOL_EXPORT_DEPENDS )
set(um6_EXEC_DEPENDS "serial" "roscpp" "sensor_msgs" "message_runtime")
set(um6_RUN_DEPENDS "serial" "roscpp" "sensor_msgs" "message_runtime")
set(um6_TEST_DEPENDS )
set(um6_DOC_DEPENDS )
set(um6_URL_WEBSITE "")
set(um6_URL_BUGTRACKER "")
set(um6_URL_REPOSITORY "")
set(um6_DEPRECATED "")