// Strings from navit_shipped.xml
_("Map Point")
_("Vehicle Position")
_("Map Point")
_("Main menu")
_("Show\nMap")
_("Settings")
_("Tools")
_("Route")
_("About")
_("Quit")
_("Actions")
_("Bookmarks")
_("Former\nDestinations")
_("Town")
_("Coordinates")
_("Stop\nNavigation")
_("Settings")
_("Display")
_("Maps")
_("Maps")
_("Vehicle")
_("Vehicle")
_("Rules")
_("Display")
_("Layout")
_("Layout")
_("Fullscreen")
_("Window Mode")
_("3D")
_("2D")
_("Auto zoom")
_("Manual zoom")
_("Layers")
_("Tools")
_("Show Locale")
_("Network info")
_("Route")
_("Zoom to route")
_("Description")
_("Height Profile")
_("Waypoints")
_("Drop last \nWaypoint")
_("Drop next \nWaypoint")
_("Map Point")
_("Layout")
_("Maps")
_("Layers")
_("Vehicle")
_("Satellite Status")
_("NMEA Data")
_("car")
_("car_shortest")
_("car_avoid_tolls")
_("car_pedantic")
_("bike")
_("pedestrian")
_("horse")
_("Truck")
